### ISSUE TITLE
problem with setup.py

### ISSUE THREAD

**Issue by Zawarud** [jupyter-xeus/xeus-python-wheel#20]
i try to run setup.py but give me this error:
```
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "c:\users\dio\appdata\local\programs\python\python38\lib\distutils\fancy_getopt.py", line 233, in getopt
    opts, args = getopt.getopt(args, short_opts, self.long_opts)
  File "c:\users\dio\appdata\local\programs\python\python38\lib\getopt.py", line 95, in getopt
    opts, args = do_shorts(opts, args[0][1:], shortopts, args[1:])
  File "c:\users\dio\appdata\local\programs\python\python38\lib\getopt.py", line 195, in do_shorts
    if short_has_arg(opt, shortopts):
  File "c:\users\dio\appdata\local\programs\python\python38\lib\getopt.py", line 211, in short_has_arg
    raise GetoptError(_('option -%s not recognized') % opt, opt)
getopt.GetoptError: option -f not recognized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\dio\appdata\local\programs\python\python38\lib\distutils\core.py", line 134, in setup
    ok = dist.parse_command_line()
  File "c:\users\dio\appdata\local\programs\python\python38\lib\site-packages\setuptools\dist.py", line 705, in parse_command_line
    result = _Distribution.parse_command_line(self)
  File "c:\users\dio\appdata\local\programs\python\python38\lib\distutils\dist.py", line 475, in parse_command_line
    args = parser.getopt(args=self.script_args, object=self)
  File "c:\users\dio\appdata\local\programs\python\python38\lib\distutils\fancy_getopt.py", line 235, in getopt
    raise DistutilsArgError(msg)
distutils.errors.DistutilsArgError: option -f not recognized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\dio\appdata\local\programs\python\python38\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-5ea678532c89>", line 24, in <module>
    setup(
  File "c:\users\dio\appdata\local\programs\python\python38\lib\site-packages\skbuild\setuptools_wrap.py", line 456, in setup
    return upstream_setup(*args, **kw)
  File "c:\users\dio\appdata\local\programs\python\python38\lib\site-packages\setuptools\__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "c:\users\dio\appdata\local\programs\python\python38\lib\distutils\core.py", line 136, in setup
    raise SystemExit(gen_usage(dist.script_name) + "\nerror: %s" % msg)
SystemExit: usage: ipykernel_launcher.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: ipykernel_launcher.py --help [cmd1 cmd2 ...]
   or: ipykernel_launcher.py --help-commands
   or: ipykernel_launcher.py cmd --help

error: option -f not recognized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\dio\appdata\local\programs\python\python38\lib\site-packages\IPython\core\ultratb.py", line 1148, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "c:\users\dio\appdata\local\programs\python\python38\lib\site-packages\IPython\core\ultratb.py", line 316, in wrapped
    return f(*args, **kwargs)
  File "c:\users\dio\appdata\local\programs\python\python38\lib\site-packages\IPython\core\ultratb.py", line 350, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "c:\users\dio\appdata\local\programs\python\python38\lib\inspect.py", line 1503, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
AttributeError: 'tuple' object has no attribute 'tb_frame'
```

**Comment by JohanMabille** [comment]
This package is for building a wheel for `xeus-python`. You need to have `scikit-build` and `cmake` installed, and then you can build the wheel:

```bash
python setup.py bdist_wheel
pip install dist/....
```

**Comment by Zawarud** [comment]
i write
`python setup.py bdist_wheel`
i had install NASM.
and the output is : 
```
[1/4] Performing configure step for 'openssl'
FAILED: openssl-prefix/src/openssl-stamp/openssl-configure
cmd.exe /C "cd /D C:\Users\DIO\Downloads\xeus-python-wheel-master\_skbuild\win-amd64-3.7\cmake-build\OpenSSL-download\openssl-src && perl configure VC-WIN64A CC=cl RC=rc --prefix=C:/Users/DIO/Downloads/xeus-python-wheel-master/_skbuild/win-amd64-3.7/cmake-install --openssldir=C:/Users/DIO/Downloads/xeus-python-wheel-master/_skbuild/win-amd64-3.7/cmake-install && "C:\Program Files\CMake\bin\cmake.exe" -E touch C:/Users/DIO/Downloads/xeus-python-wheel-master/_skbuild/win-amd64-3.7/cmake-build/OpenSSL-download/openssl-prefix/src/openssl-stamp/openssl-configure"
Configuring OpenSSL version 1.1.1d (0x1010104fL) for VC-WIN64A
Using os-specific seed configuration

Failure!  build file wasn't produced.
Please read INSTALL and associated NOTES files.  You may also have to look over
your available compiler tool chain or change your configuration.

NASM not found - make sure it's installed and available on %PATH%
ninja: build stopped: subcommand failed.
CMake Error at CMakeLists.txt:44 (message):
  CMake step for OpenSSL failed: 1


-- Configuring incomplete, errors occurred!
See also "C:/Users/DIO/Downloads/xeus-python-wheel-master/_skbuild/win-amd64-3.7/cmake-build/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "C:\Users\DIO\AppData\Local\Programs\Python\Python37\lib\site-packages\skbuild\setuptools_wrap.py", line 574, in setup
    languages=cmake_languages
  File "C:\Users\DIO\AppData\Local\Programs\Python\Python37\lib\site-packages\skbuild\cmaker.py", line 232, in configure
    os.path.abspath(CMAKE_BUILD_DIR())))

An error occurred while configuring with CMake.
  Command:
    "cmake" "C:\Users\DIO\Downloads\xeus-python-wheel-master" "-G" "Ninja" "-DCMAKE_INSTALL_PREFIX:PATH=C:\Users\DIO\Downloads\xeus-python-wheel-master\_skbuild\win-amd64-3.7\cmake-install" "-DPYTHON_EXECUTABLE:FILEPATH=C:\Users\DIO\AppData\Local\Programs\Python\Python37\python.exe" "-DPYTHON_VERSION_STRING:STRING=3.7.6" "-DPYTHON_INCLUDE_DIR:PATH=C:\Users\DIO\AppData\Local\Programs\Python\Python37\Include" "-DPYTHON_LIBRARY:FILEPATH=C:\Users\DIO\AppData\Local\Programs\Python\Python37\libs\python37.lib" "-DSKBUILD:BOOL=TRUE" "-DCMAKE_MODULE_PATH:PATH=C:\Users\DIO\AppData\Local\Programs\Python\Python37\lib\site-packages\skbuild\resources\cmake" "-DCMAKE_INSTALL_LIBDIR=lib" "-DPYTHON_EXECUTABLE:FILEPATH=C:\Users\DIO\AppData\Local\Programs\Python\Python37\python.exe" "-DCMAKE_BUILD_TYPE:STRING=Release"
  Source directory:
    C:\Users\DIO\Downloads\xeus-python-wheel-master
  Working directory:
    C:\Users\DIO\Downloads\xeus-python-wheel-master\_skbuild\win-amd64-3.7\cmake-build
Please see CMake's output for more information.
```

**Comment by JohanMabille** [comment]
If you installed NASM, it looks like it is not in the %PATH%.

**Comment by Zawarud** [comment]
I do this and install perl. But give me other error. I will wait for the compiled package.

**Comment by JohanMabille** [comment]
It might be a better option, especially if you consider that we are still iterating on it and patching upstream packages to get a wheel that will not break installed environments (by overwriting dependencies such as zmq for instance).

Stay tuned, we are closed to having something that works!
