### ISSUE TITLE
local build fails

### ISSUE THREAD

**Issue by nivcoh** [jupyter-xeus/xeus-python-wheel#55]
Hi, 
I'm struggling to build a wheel locally on windows 10 (executed from Developer cmd for VS2019). It's not going so easy but after overcoming many missing dependencies I ended up here. the error doesn't provide any good information I can proceed with and I thought it might be interesting to investigate. 

Here is the last part of the execution, where it fails:

Configuring Project
    Working directory:
      C:\gitHub\clones\xeus-python-wheel\_skbuild\win-amd64-3.7\cmake-build
    Command:
      cmake 'C:\gitHub\clones\xeus-python-wheel' -G Ninja '-DCMAKE_INSTALL_PREFIX:PATH=C:\gitHub\clones\xeus-python-wheel\_skbuild\win-amd64-3.7\cmake-install' '-DPYTHON_EXECUTABLE:FILEPATH=c:\users\cohenniv\appdata\local\programs\python\python37\python.exe' -DPYTHON_VERSION_STRING:STRING=3.7.4 '-DPYTHON_INCLUDE_DIR:PATH=c:\users\cohenniv\appdata\local\programs\python\python37\Include' '-DPYTHON_LIBRARY:FILEPATH=c:\users\cohenniv\appdata\local\programs\python\python37\libs\python37.lib' -DSKBUILD:BOOL=TRUE '-DCMAKE_MODULE_PATH:PATH=C:\Users\cohenniv\AppData\Local\Temp\pip-build-env-6jnztj50\overlay\Lib\site-packages\skbuild\resources\cmake' -DCMAKE_INSTALL_LIBDIR=lib '-DPYTHON_EXECUTABLE:FILEPATH=c:\users\cohenniv\appdata\local\programs\python\python37\python.exe' -DCMAKE_BUILD_TYPE:STRING=Release

  Traceback (most recent call last):

  An error occurred while configuring with CMake.
    Command:
      cmake 'C:\gitHub\clones\xeus-python-wheel' -G Ninja '-DCMAKE_INSTALL_PREFIX:PATH=C:\gitHub\clones\xeus-python-wheel\_skbuild\win-amd64-3.7\cmake-install' '-DPYTHON_EXECUTABLE:FILEPATH=c:\users\cohenniv\appdata\local\programs\python\python37\python.exe' -DPYTHON_VERSION_STRING:STRING=3.7.4 '-DPYTHON_INCLUDE_DIR:PATH=c:\users\cohenniv\appdata\local\programs\python\python37\Include' '-DPYTHON_LIBRARY:FILEPATH=c:\users\cohenniv\appdata\local\programs\python\python37\libs\python37.lib' -DSKBUILD:BOOL=TRUE '-DCMAKE_MODULE_PATH:PATH=C:\Users\cohenniv\AppData\Local\Temp\pip-build-env-6jnztj50\overlay\Lib\site-packages\skbuild\resources\cmake' -DCMAKE_INSTALL_LIBDIR=lib '-DPYTHON_EXECUTABLE:FILEPATH=c:\users\cohenniv\appdata\local\programs\python\python37\python.exe' -DCMAKE_BUILD_TYPE:STRING=Release
    Source directory:
      C:\gitHub\clones\xeus-python-wheel
    Working directory:
      C:\gitHub\clones\xeus-python-wheel\_skbuild\win-amd64-3.7\cmake-build
  Please see CMake's output for more information.
  Building wheel for xeus-python (PEP 517) ... error
  ERROR: Failed building wheel for xeus-python
Failed to build xeus-python
ERROR: Failed to build one or more wheels

**Comment by SylvainCorlay** [comment]
>I'm struggling to build a wheel locally on windows 10 

Sorry to hear that. FYI, we provide Windows conda packages on conda-forge.

Regarding the wheel, we are not publishing the windows wheels quite yet because we need to work on how we link with the MSVC redistributable runtime, but it should work locally - and it is tested in the CI,

> LNK1112: module machine type 'x64' conflicts with target machine type 'x86'

It does not seem that you are running the commend from from the correct command line tool, namely, there may be a mismatch between x64 (which we are assuming), and x86, which may be the command line tool that you picked.

**Comment by nivcoh** [comment]
Thank you @SylvainCorlay  you got it right. this time running from x64 cmd.
It seems that the libsodium-src library is missing the CMakeLists.txt file.

So, I ended up here:

```
  [5/8] Performing configure step for 'libsodium'
  FAILED: libsodium-prefix/src/libsodium-stamp/libsodium-configure
  cmd.exe /C "cd /D C:\gitHub\clones\xeus-python-wheel\_skbuild\win-amd64-3.7\cmake-build\libsodium-download\libsodium-src && C:\Users\cohenniv\AppData\Local\Temp\pip-build-env-96hps_ds\overlay\Lib\site-packages\cmake\data\bin\cmake.exe -GNinja C:/gitHub/clones/xeus-python-wheel/_skbuild/win-amd64-3.7/cmake-build/libsodium-download/libsodium-src && C:\Users\cohenniv\AppData\Local\Temp\pip-build-env-96hps_ds\overlay\Lib\site-packages\cmake\data\bin\cmake.exe -E touch C:/gitHub/clones/xeus-python-wheel/_skbuild/win-amd64-3.7/cmake-build/libsodium-download/libsodium-prefix/src/libsodium-stamp/libsodium-configure"
  CMake Error: The source directory "C:/gitHub/clones/xeus-python-wheel/_skbuild/win-amd64-3.7/cmake-build/libsodium-download/libsodium-src" does not appear to contain CMakeLists.txt.
  Specify --help for usage, or press the help button on the CMake GUI.
  ninja: build stopped: subcommand failed.
  -- Libzmq
  -- Looking for pthread.h
  -- Looking for pthread.h - found
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
  -- Found Threads: TRUE
  -- Detected ZMQ Version - 4.3.2
  -- Performing Test COMPILER_SUPPORTS_CXX11
  -- Performing Test COMPILER_SUPPORTS_CXX11 - Success
  -- Performing Test COMPILER_SUPPORTS_C11
  -- Performing Test COMPILER_SUPPORTS_C11 - Success
  -- Performing Test CXX_HAS_TAUT_WARNING
  -- Performing Test CXX_HAS_TAUT_WARNING - Success
  -- Performing Test CC_HAS_TAUT_WARNING
  -- Performing Test CC_HAS_TAUT_WARNING - Success
  -- Using tweetnacl for CURVE security
  -- Using radix tree implementation to manage subscriptions
  -- Looking for kqueue
  -- Looking for kqueue - not found
  -- Looking for epoll_create
  -- Looking for epoll_create - not found
  -- Looking for sys/types.h
  -- Looking for sys/types.h - found
  -- Looking for stdint.h
  -- Looking for stdint.h - found
  -- Looking for stddef.h
  -- Looking for stddef.h - found
  -- Check size of struct pollfd
  -- Check size of struct pollfd - failed
  -- Looking for pollset_create
  -- Looking for pollset_create - not found
  -- Looking for poll
  -- Looking for poll - not found
  -- Using polling method in I/O threads: select
  -- Using polling method in zmq_poll(er)_* API: select
  -- Using 64 bytes alignment for lock-free data structures
  -- Looking for include file windows.h
  -- Looking for include file windows.h - found
  -- Detected _WIN32_WINNT from CMAKE_SYSTEM_VERSION: 0x0A00
  -- Looking for include file condition_variable
  -- Looking for include file condition_variable - found
  -- Using condition_variable_t implementation: stl11
  -- Looking for include file ifaddrs.h
  -- Looking for include file ifaddrs.h - not found
  -- Looking for include file sys/uio.h
  -- Looking for include file sys/uio.h - not found
  -- Looking for include file sys/eventfd.h
  -- Looking for include file sys/eventfd.h - not found
  -- Looking for WSAStartup
  -- Looking for WSAStartup - found
  -- Looking for UuidCreateSequential
  -- Looking for UuidCreateSequential - found
  -- Looking for GetAdaptersAddresses
  -- Looking for GetAdaptersAddresses - found
  -- Looking for fopen in ws2
  -- Looking for fopen in ws2 - not found
  -- Looking for clock_gettime
  -- Looking for clock_gettime - not found
  -- Looking for fork
  -- Looking for fork - not found
  -- Looking for gethrtimei
  -- Looking for gethrtimei - not found
  -- Looking for mkdtemp
  -- Looking for mkdtemp - not found
  -- Looking for accept4
  -- Looking for accept4 - not found
  -- Looking for strnlen
  -- Looking for strnlen - found
  -- Performing Test HAVE_FLAG_-Wall
  -- Performing Test HAVE_FLAG_-Wall - Failed
  -- Performing Test HAVE_FLAG_-Wextra
  -- Performing Test HAVE_FLAG_-Wextra - Failed
  -- Performing Test HAVE_FLAG_-Wno-long-long
  -- Performing Test HAVE_FLAG_-Wno-long-long - Failed
  -- Performing Test HAVE_FLAG_-Wno-uninitialized
  -- Performing Test HAVE_FLAG_-Wno-uninitialized - Failed
  -- Performing Test HAVE_FLAG_-pedantic
  -- Performing Test HAVE_FLAG_-pedantic - Failed
  -- Checking whether noexcept is supported
  -- Performing Test ZMQ_HAVE_NOEXCEPT
  -- Performing Test ZMQ_HAVE_NOEXCEPT - Success
  -- Checking whether SOCK_CLOEXEC is supported
  -- Performing Test ZMQ_HAVE_SOCK_CLOEXEC
  -- Performing Test ZMQ_HAVE_SOCK_CLOEXEC - Failed
  -- Checking whether O_CLOEXEC is supported
  -- Performing Test ZMQ_HAVE_O_CLOEXEC
  -- Performing Test ZMQ_HAVE_O_CLOEXEC - Failed
  -- Checking whether SO_BINDTODEVICE is supported
  -- Performing Test ZMQ_HAVE_SO_BINDTODEVICE
  -- Performing Test ZMQ_HAVE_SO_BINDTODEVICE - Failed
  -- Checking whether SO_KEEPALIVE is supported
  -- Performing Test ZMQ_HAVE_SO_KEEPALIVE
  -- Performing Test ZMQ_HAVE_SO_KEEPALIVE - Failed
  -- Checking whether TCP_KEEPCNT is supported
  -- Performing Test ZMQ_HAVE_TCP_KEEPCNT
  -- Performing Test ZMQ_HAVE_TCP_KEEPCNT - Failed
  -- Checking whether TCP_KEEPIDLE is supported
  -- Performing Test ZMQ_HAVE_TCP_KEEPIDLE
  -- Performing Test ZMQ_HAVE_TCP_KEEPIDLE - Failed
  -- Checking whether TCP_KEEPINTVL is supported
  -- Performing Test ZMQ_HAVE_TCP_KEEPINTVL
  -- Performing Test ZMQ_HAVE_TCP_KEEPINTVL - Failed
  -- Checking whether TCP_KEEPALIVE is supported
  -- Performing Test ZMQ_HAVE_TCP_KEEPALIVE
  -- Performing Test ZMQ_HAVE_TCP_KEEPALIVE - Failed
  -- Checking whether TIPC is supported
  -- Performing Test ZMQ_HAVE_TIPC
  -- Performing Test ZMQ_HAVE_TIPC - Failed
  -- Checking pthread_setname signature
  -- Performing Test ZMQ_HAVE_PTHREAD_SETNAME_1
  -- Performing Test ZMQ_HAVE_PTHREAD_SETNAME_1 - Failed
  -- Performing Test ZMQ_HAVE_PTHREAD_SETNAME_2
  -- Performing Test ZMQ_HAVE_PTHREAD_SETNAME_2 - Success
  -- Performing Test ZMQ_HAVE_PTHREAD_SETNAME_3
  -- Performing Test ZMQ_HAVE_PTHREAD_SETNAME_3 - Failed
  -- Performing Test ZMQ_HAVE_PTHREAD_SET_NAME
  -- Performing Test ZMQ_HAVE_PTHREAD_SET_NAME - Failed
  -- Checking pthread_setaffinity signature
  -- Performing Test ZMQ_HAVE_PTHREAD_SETAFFINITY
  -- Performing Test ZMQ_HAVE_PTHREAD_SETAFFINITY - Failed
  -- Checking whether getrandom is supported
  -- Performing Test ZMQ_HAVE_GETRANDOM
  -- Performing Test ZMQ_HAVE_GETRANDOM - Failed
  -- Could NOT find AsciiDoc (missing: ASCIIDOC_EXECUTABLE)
  -- Fetching cppzmq
  -- Detected CPPZMQ Version - 4.7.0
  -- cppzmq v4.7.0
  -- Fetching nlohmann_json
  -- Using the single-header code from C:/gitHub/clones/xeus-python-wheel/_skbuild/win-amd64-3.7/cmake-build/_deps/nlohmann_json-src/single_include/
  -- Fetching xtl
  -- xtl v0.6.12
  -- Fetching xeus
  -- xeus version: v0.23.13
  -- xeus binary version: v1.0.0
  -- Found OpenSSL: C:/gitHub/clones/xeus-python-wheel/_skbuild/win-amd64-3.7/cmake-install/lib/libcrypto.lib (found version "1.1.1d")
  CMake Error at C:/Users/cohenniv/AppData/Local/Temp/pip-build-env-96hps_ds/overlay/Lib/site-packages/cmake/data/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
    Could NOT find sodium (missing: sodium_LIBRARY_RELEASE sodium_LIBRARY_DEBUG
    sodium_INCLUDE_DIR)
  Call Stack (most recent call first):
    C:/Users/cohenniv/AppData/Local/Temp/pip-build-env-96hps_ds/overlay/Lib/site-packages/cmake/data/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
    _skbuild/win-amd64-3.7/cmake-build/_deps/xeus-src/cmake/Findsodium.cmake:224 (find_package_handle_standard_args)
    _skbuild/win-amd64-3.7/cmake-build/_deps/xeus-src/CMakeLists.txt:207 (find_package)


  -- Configuring incomplete, errors occurred!
```

**Comment by SylvainCorlay** [comment]
hum I don't think we should require libsodium at this point on windows.

**Comment by nivcoh** [comment]
seems like this is the reason to fail... :) 
CMake Error: The source directory "C:/gitHub/clones/xeus-python-wheel/_skbuild/win-amd64-3.7/cmake-build/libsodium-download/libsodium-src" does not appear to contain CMakeLists.txt.

**Comment by SylvainCorlay** [comment]
@nivcoh I merged a PR to skip libsodium on windows and not use libsodium in zeromq.

Could you please check that this fixes your issue.

**Comment by nivcoh** [comment]
Hi @SylvainCorlay  
still fails at:   
```

  [8/8] Completed 'openssl'
  -- Libzmq
  -- Looking for pthread.h
  -- Looking for pthread.h - found
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
  -- Found Threads: TRUE
  -- Detected ZMQ Version - 4.3.2
  -- Performing Test COMPILER_SUPPORTS_CXX11
  -- Performing Test COMPILER_SUPPORTS_CXX11 - Success
  -- Performing Test COMPILER_SUPPORTS_C11
  -- Performing Test COMPILER_SUPPORTS_C11 - Success
  -- Performing Test CXX_HAS_TAUT_WARNING
  -- Performing Test CXX_HAS_TAUT_WARNING - Success
  -- Performing Test CC_HAS_TAUT_WARNING
  -- Performing Test CC_HAS_TAUT_WARNING - Success
  -- Using tweetnacl for CURVE security
  -- Using radix tree implementation to manage subscriptions
  -- Looking for kqueue
  -- Looking for kqueue - not found
  -- Looking for epoll_create
  -- Looking for epoll_create - not found
  -- Looking for sys/types.h
  -- Looking for sys/types.h - found
  -- Looking for stdint.h
  -- Looking for stdint.h - found
  -- Looking for stddef.h
  -- Looking for stddef.h - found
  -- Check size of struct pollfd
  -- Check size of struct pollfd - failed
  -- Looking for pollset_create
  -- Looking for pollset_create - not found
  -- Looking for poll
  -- Looking for poll - not found
  -- Using polling method in I/O threads: select
  -- Using polling method in zmq_poll(er)_* API: select
  -- Using 64 bytes alignment for lock-free data structures
  -- Looking for include file windows.h
  -- Looking for include file windows.h - found
  -- Detected _WIN32_WINNT from CMAKE_SYSTEM_VERSION: 0x0A00
  -- Looking for include file condition_variable
  -- Looking for include file condition_variable - found
  -- Using condition_variable_t implementation: stl11
  -- Looking for include file ifaddrs.h
  -- Looking for include file ifaddrs.h - not found
  -- Looking for include file sys/uio.h
  -- Looking for include file sys/uio.h - not found
  -- Looking for include file sys/eventfd.h
  -- Looking for include file sys/eventfd.h - not found
  -- Looking for WSAStartup
  -- Looking for WSAStartup - found
  -- Looking for UuidCreateSequential
  -- Looking for UuidCreateSequential - found
  -- Looking for GetAdaptersAddresses
  -- Looking for GetAdaptersAddresses - found
  -- Looking for fopen in ws2
  -- Looking for fopen in ws2 - not found
  -- Looking for clock_gettime
  -- Looking for clock_gettime - not found
  -- Looking for fork
  -- Looking for fork - not found
  -- Looking for gethrtimei
  -- Looking for gethrtimei - not found
  -- Looking for mkdtemp
  -- Looking for mkdtemp - not found
  -- Looking for accept4
  -- Looking for accept4 - not found
  -- Looking for strnlen
  -- Looking for strnlen - found
  -- Performing Test HAVE_FLAG_-Wall
  -- Performing Test HAVE_FLAG_-Wall - Failed
  -- Performing Test HAVE_FLAG_-Wextra
  -- Performing Test HAVE_FLAG_-Wextra - Failed
  -- Performing Test HAVE_FLAG_-Wno-long-long
  -- Performing Test HAVE_FLAG_-Wno-long-long - Failed
  -- Performing Test HAVE_FLAG_-Wno-uninitialized
  -- Performing Test HAVE_FLAG_-Wno-uninitialized - Failed
  -- Performing Test HAVE_FLAG_-pedantic
  -- Performing Test HAVE_FLAG_-pedantic - Failed
  -- Checking whether noexcept is supported
  -- Performing Test ZMQ_HAVE_NOEXCEPT
  -- Performing Test ZMQ_HAVE_NOEXCEPT - Success
  -- Checking whether SOCK_CLOEXEC is supported
  -- Performing Test ZMQ_HAVE_SOCK_CLOEXEC
  -- Performing Test ZMQ_HAVE_SOCK_CLOEXEC - Failed
  -- Checking whether O_CLOEXEC is supported
  -- Performing Test ZMQ_HAVE_O_CLOEXEC
  -- Performing Test ZMQ_HAVE_O_CLOEXEC - Failed
  -- Checking whether SO_BINDTODEVICE is supported
  -- Performing Test ZMQ_HAVE_SO_BINDTODEVICE
  -- Performing Test ZMQ_HAVE_SO_BINDTODEVICE - Failed
  -- Checking whether SO_KEEPALIVE is supported
  -- Performing Test ZMQ_HAVE_SO_KEEPALIVE
  -- Performing Test ZMQ_HAVE_SO_KEEPALIVE - Failed
  -- Checking whether TCP_KEEPCNT is supported
  -- Performing Test ZMQ_HAVE_TCP_KEEPCNT
  -- Performing Test ZMQ_HAVE_TCP_KEEPCNT - Failed
  -- Checking whether TCP_KEEPIDLE is supported
  -- Performing Test ZMQ_HAVE_TCP_KEEPIDLE
  -- Performing Test ZMQ_HAVE_TCP_KEEPIDLE - Failed
  -- Checking whether TCP_KEEPINTVL is supported
  -- Performing Test ZMQ_HAVE_TCP_KEEPINTVL
  -- Performing Test ZMQ_HAVE_TCP_KEEPINTVL - Failed
  -- Checking whether TCP_KEEPALIVE is supported
  -- Performing Test ZMQ_HAVE_TCP_KEEPALIVE
  -- Performing Test ZMQ_HAVE_TCP_KEEPALIVE - Failed
  -- Checking whether TIPC is supported
  -- Performing Test ZMQ_HAVE_TIPC
  -- Performing Test ZMQ_HAVE_TIPC - Failed
  -- Checking pthread_setname signature
  -- Performing Test ZMQ_HAVE_PTHREAD_SETNAME_1
  -- Performing Test ZMQ_HAVE_PTHREAD_SETNAME_1 - Failed
  -- Performing Test ZMQ_HAVE_PTHREAD_SETNAME_2
  -- Performing Test ZMQ_HAVE_PTHREAD_SETNAME_2 - Success
  -- Performing Test ZMQ_HAVE_PTHREAD_SETNAME_3
  -- Performing Test ZMQ_HAVE_PTHREAD_SETNAME_3 - Failed
  -- Performing Test ZMQ_HAVE_PTHREAD_SET_NAME
  -- Performing Test ZMQ_HAVE_PTHREAD_SET_NAME - Failed
  -- Checking pthread_setaffinity signature
  -- Performing Test ZMQ_HAVE_PTHREAD_SETAFFINITY
  -- Performing Test ZMQ_HAVE_PTHREAD_SETAFFINITY - Failed
  -- Checking whether getrandom is supported
  -- Performing Test ZMQ_HAVE_GETRANDOM
  -- Performing Test ZMQ_HAVE_GETRANDOM - Failed
  -- Could NOT find AsciiDoc (missing: ASCIIDOC_EXECUTABLE)
  -- Fetching cppzmq
  -- Detected CPPZMQ Version - 4.7.0
  -- cppzmq v4.7.0
  -- Fetching nlohmann_json
  -- Using the single-header code from C:/gitHub/clones/xeus-python-wheel/_skbuild/win-amd64-3.7/cmake-build/_deps/nlohmann_json-src/single_include/
  -- Fetching xtl
  -- xtl v0.6.12
  -- Fetching xeus
  -- xeus version: v0.23.13
  -- xeus binary version: v1.0.0
  -- Found OpenSSL: C:/gitHub/clones/xeus-python-wheel/_skbuild/win-amd64-3.7/cmake-install/lib/libcrypto.lib (found version "1.1.1d")
  CMake Error at C:/Users/cohenniv/AppData/Local/Temp/pip-build-env-44nesluk/overlay/Lib/site-packages/cmake/data/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
    Could NOT find sodium (missing: sodium_LIBRARY_RELEASE sodium_LIBRARY_DEBUG
    sodium_INCLUDE_DIR)
  Call Stack (most recent call first):
    C:/Users/cohenniv/AppData/Local/Temp/pip-build-env-44nesluk/overlay/Lib/site-packages/cmake/data/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
    _skbuild/win-amd64-3.7/cmake-build/_deps/xeus-src/cmake/Findsodium.cmake:224 (find_package_handle_standard_args)
    _skbuild/win-amd64-3.7/cmake-build/_deps/xeus-src/CMakeLists.txt:207 (find_package)


  -- Configuring incomplete, errors occurred!
  See also "C:/gitHub/clones/xeus-python-wheel/_skbuild/win-amd64-3.7/cmake-build/CMakeFiles/CMakeOutput.log".
  See also "C:/gitHub/clones/xeus-python-wheel/_skbuild/win-amd64-3.7/cmake-build/CMakeFiles/CMakeError.log".
  c:\users\cohenniv\appdata\local\programs\python\python37\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'cmake_process_manifest_hook'
    warnings.warn(msg)
    File "C:\Users\cohenniv\AppData\Local\Temp\pip-build-env-44nesluk\overlay\Lib\site-packages\skbuild\setuptools_wrap.py", line 586, in setup
      languages=cmake_languages
    File "C:\Users\cohenniv\AppData\Local\Temp\pip-build-env-44nesluk\overlay\Lib\site-packages\skbuild\cmaker.py", line 240, in configure
      os.path.abspath(CMAKE_BUILD_DIR())))


  --------------------------------------------------------------------------------
  -- Trying "Ninja (Visual Studio 15 2017 Win64 v141)" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "Ninja (Visual Studio 15 2017 Win64 v141)" generator - success
  --------------------------------------------------------------------------------

  Configuring Project
    Working directory:
      C:\gitHub\clones\xeus-python-wheel\_skbuild\win-amd64-3.7\cmake-build
    Command:
      cmake 'C:\gitHub\clones\xeus-python-wheel' -G Ninja '-DCMAKE_INSTALL_PREFIX:PATH=C:\gitHub\clones\xeus-python-wheel\_skbuild\win-amd64-3.7\cmake-install' '-DPYTHON_EXECUTABLE:FILEPATH=c:\users\cohenniv\appdata\local\programs\python\python37\python.exe' -DPYTHON_VERSION_STRING:STRING=3.7.4 '-DPYTHON_INCLUDE_DIR:PATH=c:\users\cohenniv\appdata\local\programs\python\python37\Include' '-DPYTHON_LIBRARY:FILEPATH=c:\users\cohenniv\appdata\local\programs\python\python37\libs\python37.lib' -DSKBUILD:BOOL=TRUE '-DCMAKE_MODULE_PATH:PATH=C:\Users\cohenniv\AppData\Local\Temp\pip-build-env-44nesluk\overlay\Lib\site-packages\skbuild\resources\cmake' -DCMAKE_INSTALL_LIBDIR=lib '-DPYTHON_EXECUTABLE:FILEPATH=c:\users\cohenniv\appdata\local\programs\python\python37\python.exe' -DCMAKE_BUILD_TYPE:STRING=Release

  Traceback (most recent call last):

  An error occurred while configuring with CMake.
    Command:
      cmake 'C:\gitHub\clones\xeus-python-wheel' -G Ninja '-DCMAKE_INSTALL_PREFIX:PATH=C:\gitHub\clones\xeus-python-wheel\_skbuild\win-amd64-3.7\cmake-install' '-DPYTHON_EXECUTABLE:FILEPATH=c:\users\cohenniv\appdata\local\programs\python\python37\python.exe' -DPYTHON_VERSION_STRING:STRING=3.7.4 '-DPYTHON_INCLUDE_DIR:PATH=c:\users\cohenniv\appdata\local\programs\python\python37\Include' '-DPYTHON_LIBRARY:FILEPATH=c:\users\cohenniv\appdata\local\programs\python\python37\libs\python37.lib' -DSKBUILD:BOOL=TRUE '-DCMAKE_MODULE_PATH:PATH=C:\Users\cohenniv\AppData\Local\Temp\pip-build-env-44nesluk\overlay\Lib\site-packages\skbuild\resources\cmake' -DCMAKE_INSTALL_LIBDIR=lib '-DPYTHON_EXECUTABLE:FILEPATH=c:\users\cohenniv\appdata\local\programs\python\python37\python.exe' -DCMAKE_BUILD_TYPE:STRING=Release
    Source directory:
      C:\gitHub\clones\xeus-python-wheel
    Working directory:
      C:\gitHub\clones\xeus-python-wheel\_skbuild\win-amd64-3.7\cmake-build
  Please see CMake's output for more information.
  Building wheel for xeus-python (PEP 517) ... error
  ERROR: Failed building wheel for xeus-python
```

**Comment by SylvainCorlay** [comment]
OK looking into it.

(Not easy because I don't reproduce it locally or on CI)

**Comment by SylvainCorlay** [comment]
Did you clean up your _skbuild directory before rebuilding?

**Comment by nivcoh** [comment]
yes, actually before the build I deleted everything and did fresh clone just to be sure.

**Comment by jeffwji** [comment]
Same issue encountered:

```


  -- Configuring incomplete, errors occurred!
  See also "C:/Temp/pip-req-build-0jrli1vv/_skbuild/win32-3.9/cmake-build/CMakeFiles/CMakeOutput.log".
    File "C:\Temp\pip-build-env-byaqnuqm\overlay\Lib\site-packages\skbuild\setuptools_wrap.py", line 582, in setup
      env = cmkr.configure(cmake_args,
    File "C:\Temp\pip-build-env-byaqnuqm\overlay\Lib\site-packages\skbuild\cmaker.py", line 229, in configure
      raise SKBuildError(


  --------------------------------------------------------------------------------
  -- Trying "Ninja (Visual Studio 15 2017 Win64 v141)" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "Ninja (Visual Studio 15 2017 Win64 v141)" generator - success
  --------------------------------------------------------------------------------

  Configuring Project
    Working directory:
      C:\Temp\pip-req-build-0jrli1vv\_skbuild\win32-3.9\cmake-build
    Command:
      cmake 'C:\Temp\pip-req-build-0jrli1vv' -G Ninja '-DCMAKE_INSTALL_PREFIX:PATH=C:\Temp\pip-req-build-0jrli1vv\_skbuild\win32-3.9\cmake-install' '-DPYTHON_EXECUTABLE:FILEPATH=d:\mycode\python\caicaisklearn\.venv\scripts\python.exe' -DPYTHON_VERSION_STRING:STRING=3.9.0 '-DPYTHON_INCLUDE_DIR:PATH=C:\Users\wangji\AppData\Local\Programs\Python\Python39\Include' '-DPYTHON_LIBRARY:FILEPATH=C:\Users\wangji\AppData\Local\Programs\Python\Python39\libs\python39.lib' -DSKBUILD:BOOL=TRUE '-DCMAKE_MODULE_PATH:PATH=C:\Temp\pip-build-env-byaqnuqm\overlay\Lib\site-packages\skbuild\resources\cmake' -DCMAKE_INSTALL_LIBDIR=lib '-DPYTHON_EXECUTABLE:FILEPATH=d:\mycode\python\caicaisklearn\.venv\scripts\python.exe' -DCMAKE_BUILD_TYPE:STRING=Release

  Traceback (most recent call last):

  An error occurred while configuring with CMake.
    Command:
      cmake 'C:\Temp\pip-req-build-0jrli1vv' -G Ninja '-DCMAKE_INSTALL_PREFIX:PATH=C:\Temp\pip-req-build-0jrli1vv\_skbuild\win32-3.9\cmake-install' '-DPYTHON_EXECUTABLE:FILEPATH=d:\mycode\python\caicaisklearn\.venv\scripts\python.exe' -DPYTHON_VERSION_STRING:STRING=3.9.0 '-DPYTHON_INCLUDE_DIR:PATH=C:\Users\wangji\AppData\Local\Programs\Python\Python39\Include' '-DPYTHON_LIBRARY:FILEPATH=C:\Users\wangji\AppData\Local\Programs\Python\Python39\libs\python39.lib' -DSKBUILD:BOOL=TRUE '-DCMAKE_MODULE_PATH:PATH=C:\Temp\pip-build-env-byaqnuqm\overlay\Lib\site-packages\skbuild\resources\cmake' -DCMAKE_INSTALL_LIBDIR=lib '-DPYTHON_EXECUTABLE:FILEPATH=d:\mycode\python\caicaisklearn\.venv\scripts\python.exe' -DCMAKE_BUILD_TYPE:STRING=Release
    Source directory:
      C:\Temp\pip-req-build-0jrli1vv
    Working directory:
      C:\Temp\pip-req-build-0jrli1vv\_skbuild\win32-3.9\cmake-build
  Please see CMake's output for more information.
  ----------------------------------------
  ERROR: Failed building wheel for xeus-python
Failed to build xeus-python
ERROR: Could not build wheels for xeus-python which use PEP 517 and cannot be installed directly
```

I'm trying install xeus-python from:

```
pip install git+https://github.com/jupyter-xeus/xeus-python-wheel.git
```
